version: '3.8'

services:
  neet_alert_bot:
    build: .
    container_name: neet_alert_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./pdf_images:/app/pdf_images
    restart: unless-stopped